server:
  port: 8095
  servlet:
    context-path: /notification-service
spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: hbconnex2000@gmail.com
    password: ljvliyodsrwkhjii
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
subject: Appointment-Confirmation
default-email: hbconnex2000@gmail.com
default-text: Your Appointment is confirmed and your booking date is on